### ISSUE TITLE
[BUG] : script.js file not linked properly

### ISSUE THREAD

**Issue by mangalgithub** [bhaavvya/Quiz#14]
There is the bug in linking the script.js with the index.html.
I want to fix that issue.
Pls assign this issue to me.

**Comment by bhaavvya** [comment]
Go for it @mangalgithub 🔥

**Comment by bhaavvya** [comment]
You can create pull request before 1 Oct I will merge it once the event starts.

**Comment by bhaavvya** [comment]
Do give a star to this repo ⭐

**Comment by mangalgithub** [comment]
Thanks for your support and guidance.

**Comment by Lakshay938** [comment]
@bhaavvya  Please assign this issue to me. I want to fix this bug.
