### ISSUE TITLE
Add Footer 

### ISSUE THREAD

**Issue by parthksingh1** [bhaavvya/Quiz#58]
**Is your feature request related to a problem? Please describe.**
Footers are added to:

Provide identification and document details.
Aid in navigation.
Offer contact information.
Display legal notices.
Reinforce branding.
Present calls to action.

**Comment by parthksingh1** [comment]
please assign me this issue

**Comment by bhaavvya** [comment]
no need .
its a very simple quiz app not some e-commerce website.
